### PR TITLE
Resolve #35061, and add an --upload-to argument

### PR DESCRIPTION
**Pull request by mijofa**
I added `--upload-to` so I could run this code on my personal systems.
but it doesn't break backwards compatibility or anything, so probably worth including.

I added Zebra striping & some borders to tables, screenshots shared in task email because I CBFed finding non-sensitive information to make screenshots from

### CODE REVIEW

**Comment by mijofa** [comment]
While making this pull request, I noticed https://github.com/trentbuck/gitit-bootstrap-theme/pull/2, which this should probably be considered a duplicate of.
I think mine looks better though.

**Comment by trentbuck** [comment]
Here's what I ended up with:
```css
/* Tall table QOL - keep heading onscreen */
#content thead {position:sticky;top:0}
/* Wide table QOL - zebra striping */
#content tr.even {background-color: rgba(0,0,0,0.03)}
/* Wide table QOL - highlight hover row */
#content tr:hover {background-color: rgba(255,255,0,0.125); transition: background-color 1s}
/* ??? QOL - visibly separate columns where two adjacent cells have sentences that EXACTLY fit, so they look like a single two-colun two-sentence cell. */
#content td,
#content th{border: thin solid rgb(0, 0, 0, 0.125)}
```
image

Here's what your PR looks like in same window:
image

**Comment by trentbuck** [comment]
PS: I added mine to screen.css so it's inherently entirely behind `@media(screen){}`.

**Comment by trentbuck** [comment]
Implemented as https://github.com/trentbuck/gitit-bootstrap-theme/commit/5dc7907f6622af9ae1fa8f29ba955cc7ee98a952

**Pull request closed without merging**
